### ISSUE TITLE
Weird settings

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#11]
Hi,

I've discovered a weird bug, it seems that settings are sometimes like the old version, and sometimes like the new (with sliders), very very weird, I don't know why it switches like that

Thank you

**Comment by tuomashatakka** [comment]
It's because it is bound to the onDidChangeActivePaneItem event. If the settings tab is opened initially with the editor, the hook is not triggered. There seems to be other cases as well where the hook is not triggered, I am working on fixing them :) 

For now, switching away from the settings tab and then switching back should activate them.

**Comment by tuomashatakka** [comment]
The sliders are broken for now - I am replacing them with native html slider inputs, so they should ve fine after the next update

**Comment by tuomashatakka** [comment]
Got this finally working almost always. Sometimes returns an empty view on initialization though
