### ISSUE TITLE
TabBar not sliding

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#14]
Hi,

when I use the colloapsable tree-view, it works good for the tree-view and the code buffer view, but when I come back to a fixed tree-view by clicking on the icon, the tab-view doesn't slide like the code buffer, making it a little bit hidden by the tree-view

Thank you

**Comment by tuomashatakka** [comment]
I just understood what you mean, after playing with theme settings :D The sliding should be observed more thoroughly. There is also an issue with sliding when multiple panes are present - only the active (or first, donut remember) pane is given a margin.

**Comment by alanzanattadev** [comment]
Be careful of not having a theme so dependant of the number of plugins installed or whatever, because this kind of feature can become a nightmare with multiple panes added by plugins :D

**Comment by tuomashatakka** [comment]
That is why the toggles for the panels are so small ;) But good point. I've tried to keep the dependencies and the premise as simple as possible - i even uninstalled all packagesvthe other day! (It was an accident though 😂😂) Actually tool-bar, tabs and tree-view are the only packages I've put any extra thought. Better to try to generalize everything since in atom you can make no assumptions about the architecture of plugins 😃

Good thing is it can always be disabled if it doesn't work well with a specific plugin.

**Comment by tuomashatakka** [comment]
I think this was resolved earlier already. I'll close this and reopen if it looks like this is still an issue.
