### ISSUE TITLE
Pop up asking for settings reset at every boot

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#18]
Hi,

Can you remove the pop up at atom start up, it's very annoying, or apply a condition :)

Thank you !

**Comment by tuomashatakka** [comment]
Yeah, I totally forgot to take that down when I published the last patch. Try and take it as a joke:--)  Every time it pops up, I personally like to wonder if that kind of "feature" would end up in some commercial project's code - it helps me to cope with it since I'm so lazy I still haven't been able to remove it :---)

**Comment by tuomashatakka** [comment]
This was fixed in 0.5.7 :)
