### ISSUE TITLE
Google Font API Key

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#23]
Hi,

Can you give us a generic one, annoying to have to create a google font project for this to be used :D 

Thank you

**Comment by tuomashatakka** [comment]
There is a comment regarding this (inline in the code) - There is a request limit for the font queries of 10000/day and I'm not willing to take a risk of waking up one morning just to notice that there is a $100 bill from google 😀

The font data is included in the package so in order to use google web fonts one does not need the key - it's just for updating the listing. I haven't had the time to take a look into the font loading and I disabled it in the most recent release. Now that I have the base for custom settings view, I can finally start working on otter things 👌

**Comment by tuomashatakka** [comment]
This was patched in the latest v0.7.0 release, in the commit 0b559c20a347f1ae11274e78fdba85259d848022. Damn I suck at using references to issues in the commit messages 😧 

provide-fonts task now writes the font face file without any http requests.
